### ISSUE TITLE
removeFooterView和addFooterView方法不能改变footer样式

### ISSUE THREAD

**Issue by loganguo** [dinuscxj/RecyclerRefreshLayout#16]
调用DefaultTipsHelper中的`getHeaderAdapter().removeFooterView`方法时出现问题。
DefaultTipsHelper中的showHasMore方法用来显示加载中的样式，我想新增一种样式用来显示“没有更多数据了”比如叫showNoMore，参考DefaultTipsHelper中的实现，showNoMore中的具体实现是：
- `mFragment.getHeaderAdapter().removeFooterView(mLoadingView);`
-  `mFragment.getHeaderAdapter().addFooterView(mNoMoreView);`
但是页面仍然显示的是mLoadingView，为什么mNoMoreView显示不出来呢？

另外，调用removeAllFooterView也无效。

错误日志是
```
cn.com.something.ui.adapter.RecyclerListAdapter$ViewHolderFactory.onCreateViewHolder(android.view.ViewGroup)' on a null object reference
W/System.err( 2855): 	at cn.com.something.ui.adapter.RecyclerListAdapter.onCreateViewHolder(RecyclerListAdapter.java:30)
W/System.err( 2855): 	at cn.com.something.ui.adapter.RecyclerListAdapter.onCreateViewHolder(RecyclerListAdapter.java:10)
W/System.err( 2855): 	at cn.com.something.ui.adapter.HeaderViewRecyclerAdapter.onCreateViewHolder(HeaderViewRecyclerAdapter.java:63)
W/System.err( 2855): 	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6073)
W/System.err( 2855): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5243)
W/System.err( 2855): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5153)
W/System.err( 2855): 	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2061)
W/System.err( 2855): 	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1445)
W/System.err( 2855): 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1408)
W/System.err( 2855): 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:580)
W/System.err( 2855): 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3374)
W/System.err( 2855): 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3183)
W/System.err( 2855): 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3627)
```

**Comment by dinuscxj** [comment]
你的这个异常是你没有掉用  public <F> void addViewType(Class<? extends F> clazz, ViewHolderFactory<? extends ViewHolder<? extends F>> factory) 注册相关的model
