### ISSUE TITLE
NPE in RecyclerRefreshLayout$1.applyTransformation

### ISSUE THREAD

**Issue by alexander-nikolaev** [dinuscxj/RecyclerRefreshLayout#17]
java.lang.NullPointerException
at com.dinuscxj.refresh.RecyclerRefreshLayout$1.applyTransformation(RecyclerRefreshLayout.java:122)
at android.view.animation.Animation.initializeInvalidateRegion(Animation.java:1047)
at android.view.View.drawAnimation(View.java:14210)
at android.view.View.draw(View.java:14359)

**Comment by dinuscxj** [comment]
fix  https://github.com/dinuscxj/RecyclerRefreshLayout/commit/3e6a553293959942d94cfaadd8cc8d5299bbc389 and release 2.0.5
