### ISSUE TITLE
Fragment SimpleItemRecyclerFragment{6fb84bc} not attached to Activity

### ISSUE THREAD

**Issue by selfimprW** [dinuscxj/RecyclerRefreshLayout#3]
Process: app.dinus.com.recyclerrefreshlayout, PID: 31521
                                                                                     java.lang.IllegalStateException: Fragment SimpleItemRecyclerFragment{6fb84bc} not attached to Activity
                                                                                         at android.support.v4.app.Fragment.getResources(Fragment.java:636)
                                                                                         at android.support.v4.app.Fragment.getString(Fragment.java:658)
                                                                                         at app.dinus.com.example.simplerefresh.SimpleItemRecyclerFragment.responseItemList(SimpleItemRecyclerFragment.java:96)
                                                                                         at app.dinus.com.example.simplerefresh.SimpleItemRecyclerFragment.access$100(SimpleItemRecyclerFragment.java:19)
                                                                                         at app.dinus.com.example.simplerefresh.SimpleItemRecyclerFragment$2$2.run(SimpleItemRecyclerFragment.java:79)
                                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by dinuscxj** [comment]
@selfimprW fix the demo bug
